databases:
  - name: blog_db
    databaseName: blog_db_lznc
    user: mathavan

services:
  - type: web
    name: Test2
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
